### ISSUE TITLE
Timeout for jobs executed

### ISSUE THREAD

**Issue by ArneTR** [green-coding-solutions/green-metrics-tool#23]
Currently a timeout exists only a per-command level.

Meaning that the total execution time of the whole `usage_scenario.yml` can be infinite.

Looking forward to a deployment as a service in the cloud this could block free resources too long.

An new configuration parameter shall be introduced that allows to set a total runtime limit.

**Comment by saiteja13427** [comment]
@ArneTR Would like to work on this issue as well.

**Comment by ArneTR** [comment]
Yes, very much appreciated :)

Currently we have only one timing check here: https://github.com/green-coding-berlin/green-metrics-tool/blob/dev/runner.py#L868

However the whole run should have a timeout block, which is triggererd by Runner.run()

This timeout block should be configurable through the `usage_scenario.yml` file in terms of its duration.

What is needed for this task is some testing if the timeout block triggeres appropriately. You have to setup the tool on your machine in order to tackle this task. Did you get that running yet?

**Comment by ArneTR** [comment]
Internal note: When this task is merged this timing should also be applied in the `jobs.py` to determine the interval for `clear_old_jobs()`

**Comment by saiteja13427** [comment]
@ArneTR Understood.
Yes I was not able to get the tool running on my PC but got it running on a VM so will use it and try solving this issue.
