### ISSUE TITLE
Badges caching

### ISSUE THREAD

**Issue by djesic** [green-coding-solutions/green-metrics-tool#267]
different SQL query, the averaged data is already there

**Comment by ArneTR** [comment]
Spec update: The database generates pre-calculated average values per metric provider in the phase_stats table.

A simple SQL query must be crafted that selects the 4 predetermined reporters like at the moment: https://github.com/green-coding-berlin/green-metrics-tool/blob/main/api/api.py#L253

From the phase_stats table the`metric_name` must match and the`type` must be `TOTAL`
