### ISSUE TITLE
utilization reporter for macOS

### ISSUE THREAD

**Issue by ArneTR** [green-coding-solutions/green-metrics-tool#330]
We currently have no reporter that could provide that for macOS. For linux the `cpu.utilization.procfs.system.provider.CpuUtilizationProcfsSystemProvider` reporter is used to generate that data. It acutally just reads from the `/proc/stat` file and spits out a file with timestamps and cpu utilizations.

See in the screenshot as an example. The 208 etc. means 2.08%
<img width="1162" alt="Screenshot 2023-06-15 at 7 21 01 PM" src="https://github.com/green-coding-berlin/green-metrics-tool/assets/250671/31614972-d69c-454c-8865-dfeca365ea49">

So in short: The GMT currently lacks this functionality for macOS but it could be really easily implemented I guess.

What needs to be done in the PR is a small piece of code, either C-code / Python or bash or similar, that reads the current CPU utilization from the macOS subsystem. 
We pull that in as metric provider plugin and do the refactoring to make the reporter work with the alternate data source.

@ribalba Maybe this issue is interesting for you, or we open it up as good first issue?

Do you have any idea how to easily get this data out of the macOS subsystem? Where to read cpu utilization "raw" ?

**Comment by ArneTR** [comment]
Because of https://github.com/green-coding-berlin/green-metrics-tool/pull/650 we do not have a standard working macOS test setup anymore.

I propose to prioritize this issue to have that running again.

@ribalba What is your time expectation for this task?

**Comment by dan-mm** [comment]
The common providers (XGBoost) should work, no? That one is still available in the test-config

**Comment by ribalba** [comment]
I think the power metrics provider will still work but this will only be on Mac. I will take a look next week. Is that ok @ArneTR ?

**Comment by dan-mm** [comment]
@ribalba - the providers should all still work in the cases where they work, the linked PR is more about what our "default" test setup is. Before, local tests were choosing which metric-providers to use based on people's personal config.yml file, but this had issues, so now we have a static test-config.yml. 

Currently this does not have power-metrics turned on by default, as I don't think that's a guarantee for all macos devices (I can confirm this provider doesn't work in Github mac VM's for example) - this is what Arne is referring to here, I think he would like a mac-os provider that is more or less general for all mac owners, like how we have the linux util provider

**Comment by ArneTR** [comment]
good call, I forgot about the powemetrics one ... reasons unclear :)

Before we start on this: @dan-mm Can you check if powermetrics can run on macOS and post  a screenshot on what it returns? I would be very suprised if they would remove the binary from the system ...

**Comment by ribalba** [comment]
For the record. I found a way how to get around the problem:
```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <mach/mach.h>
#include <mach/mach_host.h>
#include <unistd.h>

void X() {
    processor_info_array_t cpuInfo = NULL, prevCpuInfo = NULL;
    mach_msg_type_number_t numCpuInfo, numPrevCpuInfo;

    while(1){
        natural_t numCPUsU = 0U;
        kern_return_t err = host_processor_info(mach_host_self(), PROCESSOR_CPU_LOAD_INFO, &numCPUsU, &cpuInfo, &numCpuInfo);

        if (err == KERN_SUCCESS) {
            for (unsigned i = 0; i < numCPUsU; ++i) {
                float inUse, total;
                if (prevCpuInfo) {
                    inUse = ((cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER] - prevCpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER]) +
                            (cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM] - prevCpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM]) +
                            (cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE] - prevCpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE]));
                    total = inUse + (cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE] - prevCpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE]);
                } else {
                    inUse = cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER] + cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM] + cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE];
                    total = inUse + cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE];
                }

                printf("Core: %u Total %f\n", i, inUse / total);
            }

            if (prevCpuInfo) {
                size_t prevCpuInfoSize = sizeof(integer_t) * numPrevCpuInfo;
                vm_deallocate(mach_task_self(), (vm_address_t)prevCpuInfo, prevCpuInfoSize);
            }

            prevCpuInfo = cpuInfo;
            numPrevCpuInfo = numCpuInfo;

            cpuInfo = NULL;
            numCpuInfo = 0U;
        } else {
            fprintf(stderr, "Error FU\n");
        }

        usleep(100000);
    }
}

int main() {
    X();
    return 0;
}

```

**Comment by ribalba** [comment]
Fixed in https://github.com/green-coding-solutions/green-metrics-tool/pull/681
