### ISSUE TITLE
Feature request: support named volumes

### ISSUE THREAD

**Issue by raits** [green-coding-solutions/green-metrics-tool#750]
Currently, it seems that specifically only volumes that refer to an actual path of the disk are allowed based on the comment in the code related to volumes:
https://github.com/green-coding-solutions/green-metrics-tool/blob/2cefd817d0e2a5ec620eefabd374b381df3c7525/runner.py#L738-L748

I also found a mention related to explicitly failing named volumes in tests here: https://github.com/green-coding-solutions/green-metrics-tool/issues/182

Unfortunately I was not able to find any more information or reasoning on this topic from GitHub, so I wanted to check if this is something that could be supported or if it is a firm decision not to support named volumes moving forward?

The reason I ask is because with our current setup, we need to share some files between containers and the way it is set up in the compose file is by sharing a named volume between the two containers. We do not need access to the files outside of the containers during tests, so there has not been any reason to mount it to specific host path but rather just clean up the volume after we are done with it.

**Comment by ArneTR** [comment]
Hey @raits 

thanks for opening an issue! We love to see when people interact with our tooling and give feedback.

The GMT can use named volumes but we do not have this functionality in our free measurement cluster on https://metrics.green-coding.io

The tool must be put into the `--allow-unsafe` mode via a CLI switch. This can only be done if you run the tool on your own machine.

Please see this part of the runner.py as reference where the tool than allows arbitrary mounts:  https://github.com/green-coding-solutions/green-metrics-tool/blob/2cefd817d0e2a5ec620eefabd374b381df3c7525/runner.py#L715

Hope that answers the question. If not please follow up

**Comment by raits** [comment]
Thank you @ArneTR! I thought I had already tried the `--allow-unsafe` flag unsuccessfully, but it seems I was wrong. Adding the flag did indeed resolve the issue and allowed me to use named volumes as they are.

Regarding your hosted measurement cluster, is it possible that in the future it might also support named volumes or is that out of the question?

**Comment by raits** [comment]
Thank you again @ArneTR for the clarifications, I have my answers now :)
