### ISSUE TITLE
Update to the new Ubuntu 24.04 LTS version

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/green-metrics-tool#763]
Ubuntu 24.04 LTS has been released and we should see if everything works and update the install scripts. Also update NOP Linux. 

This is not really urgent but needs to be done at some stage. 

https://wiki.ubuntu.com/Releases

**Comment by ArneTR** [comment]
Our new cluster machine Fujitsu TX1330 M2 runs on 24.04. Validated!

https://docs.green-coding.io/docs/measuring/measurement-cluster/
