### ISSUE TITLE
Hosting GMT on EC2, Setup Help

### ISSUE THREAD

**Issue by chrischanwz** [green-coding-solutions/green-metrics-tool#882]
Hi, I am trying to run GMT on EC2 Ubuntu 24.0 (since I only have a windows laptop). Is that possible? Also I have some questions about the setup. 

1. Do I need to run the application I want to measure in a container concurrently as well as GMT? that means the 4 Containers GMT uses + whatever containers my application needs. I am not very clear on how Docker works as well thus my confusion, apologies.
2. I am getting issues regarding the API endpoint URL for GMT. I am trying to keep the setup as simple as possible; i am deploying my EC2 in a public subnet and expose the public IP address. Unsure of what i need to do regarding FE and API endpoint, and what config I have to do. I have tried using the same Public IP for both, but different ports for API and FE, but it does not work (the API swagger UI override the GMT FE) 
3. I know it is not recommended in the documentation, but is it possible if I just use 1 container for my application? It consists of a simple React FE and Express server, which then makes calls to an S3 bucket. 

Thank you so much

**Comment by ArneTR** [comment]
Hey Chris,

thanks for trying out the tool!

My first question is what you are trying to achieve. Is it just that you want to create a usage scenario somewhere and see the tool working? This can also be done on Windows. Have you seen the docs on this? https://docs.green-coding.io/docs/installation/installation-windows/

When you have the GMT running you can hand  in the resulting usage_scenario file to our cluster. We have quite some free options for measurement there.
See :
- https://metrics.green-coding.io/request.html
- https://www.green-coding.io/projects/green-metrics-tool/

If you want to run on EC2 to get at least some results you would need a bare metal box ... something like a m5.metal, because only there RAPL is exposed. However you will not get full machine energy but only CPU.
Is that what you want?

Wanted to shoot out these questions first and then happy to dive into the other questions :)

**Comment by chrischanwz** [comment]
Hi Arne, thank you for the quick reply! 

I am interested in getting an instance of GMT to run myself, so that I am able to measure my applications, run tests etc. 
Main motivation is to essentially get total carbon/energy readings, so that I am able to get greater transparency and information of how sustainable (or "Green") my applications are. (and to also do this in a very quick and reproducible way)
So for example, if i find out that one of my software applications is emitting a rather large amount of CO2, or maybe using too much energy in the Network Transmission, then I can figure out what to improve.

Some readings that I would definitely want to measure are: SCI, Network Transmission CO2 & Energy. 

I am not too clear on the RAPL technical differences - I would say my first priority is not to have very modular understanding of my emissions on machine/cpu level, but at least an overall measurement of how much emissions are my applications producing first.  - So if I simply run it on a simpler instance type, like t2.medium, will GMT not work?

I have tried the Windows setup already. but I note that it says it can only measure CPU utilization? Which would not be sufficient for me.

**Comment by ArneTR** [comment]
If you take any smaller machine than a bare metal on AWS you will have no RAPL access. You can still run GMT there, but it will capture not RAPL data.

In case you still want to use EC2 you could setup an estimation. We provide our [Cloud Energy](https://github.com/green-coding-solutions/cloud-energy) model which comes installed with GMT.

Setting this up takes a bit of work, as you need to set the correct coefficients in the `config.yml`. The explanation how to do this you can find in this repo, where we do this for a Hetzner machine: https://github.com/green-coding-solutions/carbondb-agent

2. However I believe that the easiest way forward for you is probably setting GMT just up on your box. Craft a usage_scenario file and then hand it in to our measurement cluster.
This comes with a proper power meter and setup machine.

So although Windows will only measure CPU utilization, handing it in on the cluster will then give you full power data from the machines we provide.

Feel free to follow up if I could not fully answer your question :)

**Comment by ribalba** [comment]
Can this issue be closed?

**Comment by chrischanwz** [comment]
hi , so sorry for the late reply, i have closed it. thank u so much for the help! i think this was a lot more technical than i had expected for my use case.
