### ISSUE TITLE
Link to SCI description page is broken

### ISSUE THREAD

**Issue by davidkopp** [green-coding-solutions/green-metrics-tool#983]
The GMT frontend links to https://docs.green-coding.io/docs/measuring/sci/formula
This link does not work. The correct link would be https://docs.green-coding.io/docs/measuring/sci/

![image](https://github.com/user-attachments/assets/9703db59-5c55-4345-99a9-58abc4f772a6)

**Comment by ArneTR** [comment]
TY! Fixed it now directly in main: https://github.com/green-coding-solutions/green-metrics-tool/commit/b54bab5fb0d850ad2c4f4bc601adb0dcb805ae43
